dist: xenial
language: python
sudo: required
services: [docker]
python:
  - "3.6"
before_install:
  - sudo apt-get update
install:
  - pip install pexpect pytest
  - sudo apt-get install xsel
script:
  - docker run -v $(pwd):$(pwd) -w $(pwd) snapcore/snapcraft sh -c "apt update && apt upgrade --yes && snapcraft"
  - sudo apt install --yes snapd
  - sudo snap install *.snap --dangerous
  - export LANG=C.UTF-8 && pytest tests/test_mpwcli.py
