arch:
  - amd64
  - arm64
  - armhf
  - i386
  - ppc64el
  - s390x
os: linux
services:
  - docker
language: python
branches:
  only:  # Creates a whitelist.  Any branch not in this list will not build.
    - master
python:
  - "3.5"
install:
  - python setup.py install
script:
  - python setup.py test
  - docker run -v $(pwd):/mpw snapcore/snapcraft sh -c "apt update && cd /mpw && snapcraft"
deploy:
  edge: true
  provider: snap
  snap: mpw_*.snap
  channel: edge
  on:
    branch: master
