sudo: required
services:
  - docker
language: python
python:
  - "3.5"
install:
  - python setup.py install
script:
  - python setup.py test
deploy:
  provider: snap
  snap: mpw_*.snap
  channel: edge
  provider: script
  script: docker run -v $(pwd):/mpw snapcore/snapcraft sh -c "apt update && cd /mpw && snapcraft"
  on:
    branch: master
