name: mpw
version: git
summary: Masterpassword app cli. 
description: Calculate  a site's password, when you need it. Fork of from masterpassword.app.
confinement: devmode
parts:
  mpw:
    plugin: python
    python-version: python3
    source: .
    build-packages:
        - libssl-dev
    stage-packages:
        - xsel

apps:
  mpw:
    command: bin/mpw_snap
    environment:
      LANG: C.UTF-8
    plugs:
      - x11
